"""Shared constants and utilities for the Almond Axol robot."""

from enum import Enum
from pathlib import Path


class Joint(Enum):
    """All motor joints on one arm, in control order.

    The seven arm joints (``SHOULDER_1`` through ``WRIST_3``) are collected in
    ``ARM_JOINTS``. ``GRIPPER`` is the eighth entry and is handled separately
    from the arm joints throughout the control stack.
    """

    SHOULDER_1 = "shoulder_1"
    SHOULDER_2 = "shoulder_2"
    SHOULDER_3 = "shoulder_3"
    ELBOW = "elbow"
    WRIST_1 = "wrist_1"
    WRIST_2 = "wrist_2"
    WRIST_3 = "wrist_3"
    GRIPPER = "gripper"


CAN_LEFT = "can_alm_axol_l"
CAN_RIGHT = "can_alm_axol_r"
# The powered cart's wheel bus (its own single-channel adapter, separate from
# the arm hub). NB: kernel interface names are capped at 15 chars (IFNAMSIZ),
# so this can't be the more readable "can_alm_axol_base".
CAN_BASE = "can_alm_axol_b"

ARM_JOINTS: list[Joint] = [j for j in Joint if j != Joint.GRIPPER]


URDF_PATH: Path = Path(__file__).resolve().parent / "kinematics" / "urdf" / "axol.urdf"
"""The **control** model: what the IK solver, the self-collision model, and the
MuJoCo gravity compensator all load. Its visual meshes are Almond's decimated
stand-ins — 1,084 triangles for the whole robot, with the torso (``Base.stl``,
``S1.stl``) and both grippers modelled as plain boxes."""


URDF_VISUAL_PATH: Path = URDF_PATH.with_name("axol_visual.urdf")
"""The **viewer** model: identical kinematics, but with the real gripper
geometry from Almond's published CAD and a prismatic joint per jaw, so a
commanded opening is actually visible.

Generated by ``tools/build_visual_urdf.py``; absent until that has been run,
so callers fall back to :data:`URDF_PATH`. Kept separate on purpose — adding
the four jaw joints to the control model would take its actuated count from 14
to 18 and perturb IK, collision, and gravity compensation for a purely visual
gain."""


def visual_urdf_path() -> Path:
    """The best model available for *display*, falling back to the control model."""
    return URDF_VISUAL_PATH if URDF_VISUAL_PATH.exists() else URDF_PATH


# Where the fingers close, in the gripper link frame (metres, FLU). The URDF
# chain ends at the gripper mount, which is what forward kinematics and the IK
# solver report; the gripper mesh runs 145 mm out along that link's -Z. Any
# code that cares where the *tool* is — rather than where it is bolted on —
# needs this offset, and the distance is large enough that ignoring it turns a
# straight-line move into a visible arc as the wrist reorients.
GRIPPER_TIP_OFFSET: tuple[float, float, float] = (0.0, 0.0, -0.145)


# Single source of truth for URDF joint and body names. All helpers
# (gravity comp, IK solver, simulation) compose ``f"{side}_{suffix}"`` from
# these tables via the ``urdf_*_name`` helpers below.

# ``Joint.GRIPPER`` is intentionally absent: the gripper is a fixed URDF
# joint with no actuator counterpart.
_ARM_JOINT_URDF_SUFFIX: dict[Joint, str] = {
    Joint.SHOULDER_1: "s1_0",
    Joint.SHOULDER_2: "s2_0",
    Joint.SHOULDER_3: "s3_0",
    Joint.ELBOW: "e1_0",
    Joint.WRIST_1: "e2_0",
    Joint.WRIST_2: "w1_0",
    Joint.WRIST_3: "w2_0",
}

# Body driven by each joint. ``Joint.GRIPPER`` maps to the (fixed-jointed)
# gripper link itself; MuJoCo merges this body into ``*_w2`` at load time.
_BODY_URDF_SUFFIX: dict[Joint, str] = {
    Joint.SHOULDER_1: "s2",
    Joint.SHOULDER_2: "s3",
    Joint.SHOULDER_3: "e1",
    Joint.ELBOW: "e2",
    Joint.WRIST_1: "w0",
    Joint.WRIST_2: "w1",
    Joint.WRIST_3: "w2",
    Joint.GRIPPER: "gripper",
}


def urdf_joint_name(joint: Joint, *, is_left: bool) -> str:
    """URDF revolute-joint name driving ``joint`` on the given arm.

    Example::

        urdf_joint_name(Joint.SHOULDER_1, is_left=True) == "left_s1_0"

    Raises ``KeyError`` for ``Joint.GRIPPER`` (no actuator joint in the URDF).
    """
    side = "left" if is_left else "right"
    return f"{side}_{_ARM_JOINT_URDF_SUFFIX[joint]}"


def urdf_body_name(joint: Joint, *, is_left: bool) -> str:
    """URDF body driven by ``joint`` on the given arm.

    Example::

        urdf_body_name(Joint.SHOULDER_1, is_left=True) == "left_s2"
        urdf_body_name(Joint.GRIPPER,    is_left=True) == "left_gripper"
    """
    side = "left" if is_left else "right"
    return f"{side}_{_BODY_URDF_SUFFIX[joint]}"


def urdf_arm_joint_names(*, is_left: bool) -> list[str]:
    """URDF revolute-joint names for the 7 arm joints, in :data:`ARM_JOINTS` order."""
    return [urdf_joint_name(j, is_left=is_left) for j in ARM_JOINTS]


def urdf_arm_body_names(*, is_left: bool) -> list[str]:
    """URDF bodies driven by the 7 arm joints, in :data:`ARM_JOINTS` order."""
    return [urdf_body_name(j, is_left=is_left) for j in ARM_JOINTS]
